### ISSUE TITLE
The Magic Nix Cache

### ISSUE THREAD

**Issue by PedroRegisPOAR** [brenomfviana/brado#21]
## Resumo

Seria interessante usarmos github Actions para, por exemplo, testar o pacote?

Acredito que seja relativamente simples fazer um exemplo mínimo dessa action para esse projeto.

Fontes que recomendo a leitura:
- https://determinate.systems/posts/magic-nix-cache
- https://discourse.nixos.org/t/the-magic-nix-cache-a-github-action-for-speeding-up-your-nix-workflows/29665
- https://determinate.systems/posts/nix-github-actions

**Comment by brenomfviana** [comment]
Pensei nisso também, agora que temos validação de CPF e CNPJ, acho que esse é um bom próximo passo.
