### ISSUE TITLE
Efetivamente fazer um pacote "nos termos nix": usar stdenv.mkDerivation, rustPlatform.buildRustPackage ou semelhante

### ISSUE THREAD

**Issue by PedroRegisPOAR** [brenomfviana/brado#22]
## Resumo

A forma como se está usando nix até o momento nesse projeto tem sido um dos usos mais simples do nix. Após resolver #12 e possivelmente #21 seria de muito valor ao projeto que usassemos

Exemplo do que me refiro:
```bash
mkdir foo-bar \
&& cd foo-bar \
&& nix flake init -t templates#rust-web-server \
&& nix build -L
```

Considerando que compilou, isso sim é "um pacote no ecossistema nix".

Refs.:
- https://www.tweag.io/blog/2022-09-22-rust-nix/
- https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md
- https://github.com/NixOS/nixpkgs/blob/833ccca4c1005b992dc6667be211fac72c90b40f/pkgs/tools/misc/natls/default.nix#L6
- https://github.com/willdoescode/nat

**Comment by brenomfviana** [comment]
Mover essa issue pro projeto: https://github.com/brenomfviana/brado-c
